name: Temporalite CI/CD Deployment

on:
  push:
    branches: [production, stage]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get branch name'
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Build and push image to AWS ECR'
        uses: kciter/aws-ecr-action@v3
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: temporalite
          region: us-east-1
          tags: ${{ steps.branch-name.outputs.current_branch }}